-- Run this once in Supabase Dashboard -> SQL Editor.
create table if not exists public.users (
    id bigint generated by default as identity primary key,
    username text not null unique,
    password_hash text not null,
    ip_address text not null,
    status text not null default 'active' check (status in ('active', 'blocked'))
);

    -- Remove archived rows and enforce the two supported access states.
    delete from public.users where status = 'deleted';
    alter table public.users drop constraint if exists users_status_check;
    alter table public.users add constraint users_status_check check (status in ('active', 'blocked'));

-- Remove fields from older versions of the app.
alter table public.users drop column if exists expiry;
alter table public.users drop column if exists created_at;
alter table public.users drop column if exists updated_at;

alter table public.users enable row level security;

grant select, insert, update, delete on table public.users to anon, authenticated;
grant usage, select on sequence public.users_id_seq to anon, authenticated;

drop policy if exists "apex app can read users" on public.users;
drop policy if exists "apex app can create users" on public.users;
drop policy if exists "apex app can update users" on public.users;
drop policy if exists "apex app can delete users" on public.users;

-- The app performs its own password/IP/admin checks. Keep the publishable key
-- server-side in Streamlit secrets or .env and never expose it in the frontend.
create policy "apex app can read users"
    on public.users for select to anon using (true);
create policy "apex app can create users"
    on public.users for insert to anon with check (true);
create policy "apex app can update users"
    on public.users for update to anon using (true) with check (true);
create policy "apex app can delete users"
    on public.users for delete to anon using (true);

create index if not exists users_username_idx on public.users (username);
create index if not exists users_status_idx on public.users (status);
